### ISSUE TITLE
Make SQLite one writer and one/multiple reader modes to avoid waiting connection.

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#1222]
#### Original Title: SQLiteConnectionPool﹕ The connection pool for database [...] has been unable to grant a connection [...]

----------------------------------------------

From @kombadzomba  https://github.com/couchbase/couchbase-lite-android/issues/289#issuecomment-216710117

----------------------------------------------

I am sorry if waking up this zombie thread is wrong, but I am having troubles with the similar output that was mentioned in this thread. I've tried couchbase lite libs 1.1.0, 1.2.0 and 1.2.1. 

The issue is reproducible on Nexus 5 all the time and the scenario is running a query with compound keys on a view that has around 5500 documents. I have only map function in the view:
```
emitter.emit(Arrays.asList(
    document.get("device_imei"),
    document.get("name")
), null);
```
And this is how I set start and end keys:

```
view.setStartKey(Arrays.asList(deviceIMEI, null));
view.setEndKey(Arrays.asList(deviceIMEI, new HashMap<String, Object>()));
```

The query never ends and on every 30 seconds I get output that was mentioned in the begging of this thread:

```
05-04 02:22:44.957 32550-2346/net.dzomba.termin3.stage W/database: SQLiteConnectionPool: The connection pool for database '/data/user/0/net.dzomba.termin3.stage/files/org_2.cblite2/db.sqlite3' has been unable to grant a connection to thread 5188 (RxNewThreadScheduler-3) with flags 0x1 for 360.01 seconds.
  Connections: 1 active, 0 idle, 0 available.                                                                   
  Requests in progress:
  executeForChangedRowCount started 359545ms ago - running, sql="INSERT INTO 'maps_9' (sequence, key, value) VALUES(?,?,?)" 
```
Can you please try to reproduce this?

**Comment by hideki** [comment]
Hi @kombadzomba,

Could you please provide code snippet of entire query codes and sample documents? If you could provide us small sample app, it helps us to debug a lot.

Thanks!
Hideki

**Comment by kombadzomba** [comment]
Hideki, thanks for fast actions!

Yes, I can provide some code snippets:
1. [Sample documents](https://gist.github.com/kombadzomba/09eefa9e1571736691f1d30f4185f3b8) - There are three of them shown but the rest is the same, just the name and phone_mobile fields are different. 
2. [CouchDbFacade](https://gist.github.com/kombadzomba/6e4c4fab816fb963df096edbcacad611) - Entry point
3. [ClientByNameTypeDeviceView](https://gist.github.com/kombadzomba/b1abcdcaee16f63ef57efa02809fc276) & [AbstractView](https://gist.github.com/kombadzomba/4a22689f65f94fc0e46009dd36660e2f) - The view & the query
4. [ClientEntity](https://gist.github.com/kombadzomba/f4520c5d30c94913ab8575edce44409f) & [CommonEntity](https://gist.github.com/kombadzomba/d80c428ff3b41c532db73aa0559dba06) - Document object
5. [ClientOriginCode](https://gist.github.com/kombadzomba/51f03d6c7fd4644a54cd148ed13e7c46) & [DocumentTypeCode](https://gist.github.com/kombadzomba/286e9bcfacee0c32a54ce4ae005c2215) & [Enums](https://gist.github.com/kombadzomba/b70560c488960d5464ded9ae352c0df8) - Constants

I hope this can help.

**Comment by hideki** [comment]
@kombadzomba, Thank you for providing sample doc and codes. We will try to reproduce the issue. Thanks again!

**Comment by hideki** [comment]
Hi @kombadzomba ,

I wrote the test based on your inputs. However I could not reproduce the SQLiteConnectionPool issue with it. Could you please review the test I wrote?

Test codes:
https://github.com/couchbase/couchbase-lite-android/blob/feature/issue_1222/src/androidTest/java/com/couchbase/lite/ViewsTest.java#L3351-L3422

Thanks!
Hideki

**Comment by hideki** [comment]
Could be same problem: https://github.com/couchbase/couchbase-lite-android/issues/854

**Comment by hideki** [comment]
Hi @kombadzomba,
What version of Couchbase Lite are you using? If this issue's root cause is same with the issue, couchbase/couchbase-lite-android#854, the issue is already addressed with v1.2.1. Please try v1.2.1?
Thanks!

**Comment by kombadzomba** [comment]
Hi @hideki,
Your test is perfect. 

When I run your test [peeled a little bit](https://gist.github.com/kombadzomba/7cf151461c02c94c1873c0dada2fef89) it passes. 

However, I still have the issue in production although the code looks the same. It feels like the data content in the real database may be the cause. If I succeed to create a TestCase that reproduces the issue I'll put it here in this thread.

You've asked about couchbase-lite version I use. It is 1.2.1. Few more notes that may be interesting... My build.gradle contains:
`compile fileTree(include: ['*.jar'], dir: 'libs')`
`// compile 'com.android.support:appcompat-v7:21.0.3'`
`compile 'com.couchbase.lite:couchbase-lite-android:1.2.1'`

You may notice that I've commented appcompat. I am using supportLibVersion = "23.2.1".

Regards!

**Comment by hideki** [comment]
@kombadzomba,
In general, our library is independent from android libraries. I guess it is not appcompat issue.

Next time you encounter this issue, could you please take a thread dump?

Steps to take thread-dump:
https://github.com/couchbase/couchbase-lite-android/issues/854#issuecomment-217596694

Thanks!

**Comment by kombadzomba** [comment]
[Here](https://gist.github.com/kombadzomba/7fb8d59195a62f67e301bdd0244eac52) is the Thread dump.

net.dzomba.termin3.model.couchdb.CouchDbFacade.getClientByNameTypeDevice() is the blocked method that calls the query on a view.

**Comment by kombadzomba** [comment]
[Here](https://gist.github.com/kombadzomba/5a8fbf27aea2f0856365679b3683c1ea) is another thread dump.

**Comment by kombadzomba** [comment]
Hi @hideki,

I've noticed that you have used TransactionalTask for database inserts in your test case. I am not using any in my code for updates nor inserts. That is the reason I removed database inserts and updates in my second thread dump. However that didn't help. I see that index update for the queried view is running in both thread dumps. My index update mode is: `Query.IndexUpdateMode.BEFORE`.

Regards.

**Comment by hideki** [comment]
Hi @kombadzomba,

thank you very much for capturing thread-dump. It helps me a lot.

From both thread-dumps, one thread is holding SQLite connection and busy for updating index. Another thread waits for SQLite connection.

CBL SQLite storage opens only one SQLite connection for both read and write. In case of your app, updateIndex() takes long time to finish, and it holds SQLiteConnection. Other thread can not obtain SQLiteConnection.

We are considering to change to one SQLiteConnection for writer and one SQLiteConnection for reader. So reader will not be blocked by writer. If it works, next step could be one connection for writer, and multiple connections for reader.

Thanks,
Hideki

**Comment by hideki** [comment]
Todo: 
- Make SQLite one writer and multiple reader

**Comment by hideki** [comment]
Hi @kombadzomba,

We made SQLite one writer and multiple readers mode. Maximum SQLite connection is 4. Writer is only one connection. Reader could be 1-4 connections. Reading thread should not be blocked by writer thread. 

Sorry for keep asking, could you please test 0.0.0-733 with your error scenario?

http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/0.0.0-733/
