### ISSUE TITLE
Router unable to route request to do_GET_DesignDocument (ForestDB)

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1372]
API 19 arm emulator

Failing test - possible duplicate of #1312, however, the test is failing in a different place with ForestDB+Encryption

```
W/Router  ( 4686): Caused by: com.couchbase.lite.CouchbaseLiteException, Status: 590 (HTTP 500 Database error!)
W/Router  ( 4686):  at com.couchbase.lite.store.ForestDBViewStore.updateIndexes(ForestDBViewStore.java:303)
W/Router  ( 4686):  at com.couchbase.lite.View.updateIndexes(View.java:321)
W/Router  ( 4686):  at com.couchbase.lite.View.updateIndex(View.java:294)
W/Router  ( 4686):  at com.couchbase.lite.router.Router.queryDesignDoc(Router.java:2403)
W/Router  ( 4686):  at com.couchbase.lite.router.Router.do_GET_DesignDocument(Router.java:2435)
W/Router  ( 4686):  ... 10 more
V/Listener( 4686): RouterCallbackB
```

adb output

```
I/Database( 4686): Invalid filename as a view store: filename=test%2Fbasic.viewindex.meta
I/cbforest( 4686): Database: beginTransaction
D/Listener( 4686): authHeader is null
V/Listener( 4686): Not enforcing basic auth -- allowedCredentials null or empty
V/Listener( 4686): remoteURL() addr=127.0.0.1
I/Database( 4686): Invalid filename as a view store: filename=db.forest.0
I/Database( 4686): Invalid filename as a view store: filename=db.forest.meta
I/Database( 4686): Invalid filename as a view store: filename=attachments
I/Database( 4686): Invalid filename as a view store: filename=test%2Fbasic.viewindex.meta
D/Listener( 4686): authHeader is null
E/cbforest( 4686): Assertion failed: !_inTransaction (/home/couchbase/jenkins/workspace/couchbase-lite-android-build/couchbase-lite-android/libraries/couchbase-lite-java-forestdb/jni/../vendor/cbforest/CBForest/Database.cc:274, in void cbforest::Database::beginTransaction(cbforest::Transaction *))
V/Listener( 4686): Not enforcing basic auth -- allowedCredentials null or empty
I/cbforest( 4686): Database: abort transaction
V/Listener( 4686): remoteURL() addr=127.0.0.1
I/Database( 4686): Invalid filename as a view store: filename=db.forest.0
I/Database( 4686): Invalid filename as a view store: filename=db.forest.meta
I/Database( 4686): Invalid filename as a view store: filename=attachments
I/Database( 4686): Invalid filename as a view store: filename=test%2Fbasic.viewindex.meta
I/cbforest( 4686): Database: beginTransaction
I/cbforest( 4686): Database: abort transaction
V/View    ( 4686): Query test/basic: Found row with key=cbl_views_5, value=bar, id=cbl_views_5
V/View    ( 4686): Query test/basic: Found row with key=cbl_views_6, value=bar, id=cbl_views_6
W/Router  ( 4686): Router unable to route request to do_GET_DesignDocument
W/Router  ( 4686): java.lang.reflect.InvocationTargetException
W/Router  ( 4686):  at java.lang.reflect.Method.invokeNative(Native Method)
W/Router  ( 4686):  at java.lang.reflect.Method.invoke(Method.java:515)
W/Router  ( 4686):  at com.couchbase.lite.router.Router.start(Router.java:571)
W/Router  ( 4686):  at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141)
W/Router  ( 4686):  at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
W/Router  ( 4686):  at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
W/Router  ( 4686):  at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
W/Router  ( 4686):  at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
W/Router  ( 4686):  at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
W/Router  ( 4686):  at java.lang.Thread.run(Thread.java:841)
W/Router  ( 4686): Caused by: com.couchbase.lite.CouchbaseLiteException, Status: 590 (HTTP 500 Database error!)
W/Router  ( 4686):  at com.couchbase.lite.store.ForestDBViewStore.updateIndexes(ForestDBViewStore.java:303)
W/Router  ( 4686):  at com.couchbase.lite.View.updateIndexes(View.java:321)
W/Router  ( 4686):  at com.couchbase.lite.View.updateIndex(View.java:294)
W/Router  ( 4686):  at com.couchbase.lite.router.Router.queryDesignDoc(Router.java:2403)
W/Router  ( 4686):  at com.couchbase.lite.router.Router.do_GET_DesignDocument(Router.java:2435)
W/Router  ( 4686):  ... 10 more
V/Listener( 4686): RouterCallbackBlock.onResponseReady() START
V/View    ( 4686): Query test/basic: Found row with key=cbl_views_7, value=bar, id=cbl_views_7
V/View    ( 4686): Query test/basic: Found row with key=cbl_views_8, value=bar, id=cbl_views_8
V/View    ( 4686): Query test/basic: Found row with key=cbl_views_9, value=bar, id=cbl_views_9
V/Listener( 4686): RouterCallbackBlock.onResponseReady() END
V/Listener( 4686): CountDownLatch.await() START
V/Listener( 4686): CountDownLatch.await() END
V/View    ( 4686): Query test/basic: Found row with key=cbl_views_0, value=bar, id=cbl_views_0
V/View    ( 4686): Query test/basic: Found row with key=cbl_views_1, value=bar, id=cbl_views_1
V/Listener( 4686): RouterCallbackBlock.onResponseReady() START
V/Listener( 4686): RouterCallbackBlock.onResponseReady() END
V/Listener( 4686): CountDownLatch.await() START
V/Listener( 4686): CountDownLatch.await() END
V/View    ( 4686): Query test/basic: Found row with key=cbl_views_2, value=bar, id=cbl_views_2
V/View    ( 4686): Query test/basic: Found row with key=cbl_views_3, value=bar, id=cbl_views_3
V/View    ( 4686): Query test/basic: Found row with key=cbl_views_4, value=bar, id=cbl_views_4
V/View    ( 4686): Query test/basic: Found row with key=cbl_views_5, value=bar, id=cbl_views_5
V/View    ( 4686): Query test/basic: Found row with key=cbl_views_6, value=bar, id=cbl_views_6
V/View    ( 4686): Query test/basic: Found row with key=cbl_views_7, value=bar, id=cbl_views_7
V/View    ( 4686): Query test/basic: Found row with key=cbl_views_8, value=bar, id=cbl_views_8
V/View    ( 4686): Query test/basic: Found row with key=cbl_views_9, value=bar, id=cbl_views_9
D/dalvikvm( 4686): GC_FOR_ALLOC freed 580K, 14% free 4077K/4724K, paused 31ms, total 37ms
V/Listener( 4686): RouterCallbackBlock.onResponseReady() START
V/Listener( 4686): RouterCallbackBlock.onResponseReady() END
V/Listener( 4686): CountDownLatch.await() START
V/Listener( 4686): CountDownLatch.await() END
```

Test output

```
TAP version 13
# kill LiteServ
http server started on: http://127.0.0.1:8189
# start test client
ok 1 no error, LiteServe running on our port
# create test database
ok 2 test db reachable
# simple map function
ok 3 docs_created
ok 4 can create design doc
ok 5 should be equal
ok 6 should be equal
# total_rows attribute on view query result
ok 7 key total_rows
ok 8 startkey total_rows
ok 9 keys total_rows
not ok 10 descending total_rows
  ---
    file:   /Users/sethrosetter/Code/sync-gateway-tests/node_modules/coax/node_modules/hoax/lib/hoax-core.js
    line:   19
    column: 11
    stack:
      - |
        getCaller (/Users/sethrosetter/Code/sync-gateway-tests/node_modules/tap/lib/tap-assert.js:439:17)
      - |
        assert (/Users/sethrosetter/Code/sync-gateway-tests/node_modules/tap/lib/tap-assert.js:21:16)
      - |
        Function.equal (/Users/sethrosetter/Code/sync-gateway-tests/node_modules/tap/lib/tap-assert.js:163:10)
      - |
        Test._testAssert (/Users/sethrosetter/Code/sync-gateway-tests/node_modules/tap/lib/tap-test.js:87:16)
      - |
        /Users/sethrosetter/Code/sync-gateway-tests/tests/cbl-views.js:122:11
      - |
        Request._callback (/Users/sethrosetter/Code/sync-gateway-tests/node_modules/coax/node_modules/hoax/lib/hoax-core.js:19:11)
      - |
        Request.self.callback (/Users/sethrosetter/Code/sync-gateway-tests/node_modules/coax/node_modules/hoax/node_modules/request/main.js:122:22)
      - |
        Request.emit (events.js:98:17)
      - |
        Request.<anonymous> (/Users/sethrosetter/Code/sync-gateway-tests/node_modules/coax/node_modules/hoax/node_modules/request/main.js:661:16)
      - |
        Request.emit (events.js:117:20)
    found:  ~
    wanted: 10
    type:
      found:  undefined
      wanted: undefined
  ...
ok 11 limit total_rows
ok 12 endkey total_rows
not ok 13 mixed total_rows
  ---
    file:   /Users/sethrosetter/Code/sync-gateway-tests/node_modules/coax/node_modules/hoax/lib/hoax-core.js
    line:   19
    column: 11
    stack:
      - |
        getCaller (/Users/sethrosetter/Code/sync-gateway-tests/node_modules/tap/lib/tap-assert.js:439:17)
      - |
        assert (/Users/sethrosetter/Code/sync-gateway-tests/node_modules/tap/lib/tap-assert.js:21:16)
      - |
        Function.equal (/Users/sethrosetter/Code/sync-gateway-tests/node_modules/tap/lib/tap-assert.js:163:10)
      - |
        Test._testAssert (/Users/sethrosetter/Code/sync-gateway-tests/node_modules/tap/lib/tap-test.js:87:16)
      - |
        /Users/sethrosetter/Code/sync-gateway-tests/tests/cbl-views.js:181:11
      - |
        Request._callback (/Users/sethrosetter/Code/sync-gateway-tests/node_modules/coax/node_modules/hoax/lib/hoax-core.js:19:11)
      - |
        Request.self.callback (/Users/sethrosetter/Code/sync-gateway-tests/node_modules/coax/node_modules/hoax/node_modules/request/main.js:122:22)
      - |
        Request.emit (events.js:98:17)
      - |
        Request.<anonymous> (/Users/sethrosetter/Code/sync-gateway-tests/node_modules/coax/node_modules/hoax/node_modules/request/main.js:661:16)
      - |
        Request.emit (events.js:117:20)
    found:  ~
    wanted: 10
    type:
      found:  undefined
      wanted: undefined
  ...
ok 14 update_seq total_rows
ok 15 include_docs total_rows
```

**Comment by sethrosetter** [comment]
I believe this is a regression. I'm not seeing this behavior with 1.2.1

**Comment by hideki** [comment]
Error occurs `_inTransaction` is not NULL when calling `Database::beginTransaction(Transaction* t)`.
```c++
    void Database::beginTransaction(Transaction* t) {
        CBFAssert(!_inTransaction);
        if (!isOpen())
            error::_throw(FDB_RESULT_INVALID_HANDLE);
        std::unique_lock<std::mutex> lock(_file->_transactionMutex);

```
https://github.com/couchbaselabs/cbforest/blob/master/CBForest/Database.cc#L274

Log cat
```
07-26 16:46:29.561 6551-6700/com.couchbase.liteservandroid I/cbforest: Database: beginTransaction
07-26 16:46:29.571 6551-6668/com.couchbase.liteservandroid E/cbforest: Assertion failed: !_inTransaction (/Users/hideki/github/couchbase-lite-android-liteserv/libraries/couchbase-lite-java-forestdb/jni/../vendor/cbforest/CBForest/Database.cc:274, in void cbforest::Database::beginTransaction(cbforest::Transaction *))
07-26 16:46:29.581 6551-6668/com.couchbase.liteservandroid E/ForestBridge: --------------->>>>>> ERROR: _err2status()
   com.couchbase.cbforest.ForestException: internal assertion failure
       at com.couchbase.cbforest.Indexer.beginIndex(Native Method)
       at com.couchbase.cbforest.Indexer.<init>(Indexer.java:25)
       at com.couchbase.lite.store.ForestDBViewStore.updateIndexes(ForestDBViewStore.java:247)
       at com.couchbase.lite.View.updateIndexes(View.java:321)
       at com.couchbase.lite.View.updateIndex(View.java:294)
       at com.couchbase.lite.router.Router.queryDesignDoc(Router.java:2403)
       at com.couchbase.lite.router.Router.do_GET_DesignDocument(Router.java:2435)
       at java.lang.reflect.Method.invokeNative(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.couchbase.lite.router.Router.start(Router.java:571)
       at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141)
       at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
       at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
       at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
       at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
       at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
       at java.lang.Thread.run(Thread.java:841)
07-26 16:46:29.591 6551-6701/com.couchbase.liteservandroid I/Database: Invalid filename as a view store: filename=db.forest.0
07-26 16:46:29.591 6551-6700/com.couchbase.liteservandroid I/cbforest: Database: abort transaction
07-26 16:46:29.601 6551-6699/com.couchbase.liteservandroid V/View: Query test/basic: Found row with key=cbl_views_1, value=bar, id=cbl_views_1
07-26 16:46:29.601 6551-6699/com.couchbase.liteservandroid V/View: Query test/basic: Found row with key=cbl_views_2, value=bar, id=cbl_views_2
07-26 16:46:29.611 6551-6668/com.couchbase.liteservandroid W/Router: Router unable to route request to do_GET_DesignDocument
   java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Method.invokeNative(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.couchbase.lite.router.Router.start(Router.java:571)
       at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141)
       at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
       at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
       at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
       at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
       at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
       at java.lang.Thread.run(Thread.java:841)
    Caused by: com.couchbase.lite.CouchbaseLiteException, Status: 590 (HTTP 500 Database error!)
       at com.couchbase.lite.store.ForestDBViewStore.updateIndexes(ForestDBViewStore.java:303)
       at com.couchbase.lite.View.updateIndexes(View.java:321)
       at com.couchbase.lite.View.updateIndex(View.java:294)
       at com.couchbase.lite.router.Router.queryDesignDoc(Router.java:2403)
       at com.couchbase.lite.router.Router.do_GET_DesignDocument(Router.java:2435)
       at java.lang.reflect.Method.invokeNative(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:515) 
       at com.couchbase.lite.router.Router.start(Router.java:571) 
       at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141) 
       at javax.servlet.http.HttpServlet.service(HttpServlet.java:802) 
       at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251) 
       at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176) 
       at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988) 
       at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223) 
       at java.lang.Thread.run(Thread.java:841) 
07-26 16:46:29.611 6551-6701/com.couchbase.liteservandroid I/Database: Invalid filename as a view store: filename=db.forest.meta
07-26 16:46:29.621 6551-6668/com.couchbase.liteservandroid V/Listener: RouterCallbackBlock.onResponseReady() START
```

**Comment by snej** [comment]
I think this is similar to the other bug. It looks like you can't have two indexers on the same view at the same time.

**Comment by hideki** [comment]
Thank you for your inputs!

**Comment by snej** [comment]
More generally: In CBForest if two threads try to create a transaction on the same Database object, the second one will hit this assertion failure. The mutex works for two threads on different Database objects (on the same db file), but not when they're the same object.

**Comment by snej** [comment]
Is it possible that `ForestDBViewStore.updateIndexes` was called with the same view appearing multiple times in the array? That's the only way that I can see this happening.

**Comment by hideki** [comment]
I am adding following logging codes in `updateIndexes(...)`
```java
    @Override
    public Status updateIndexes(List<ViewStore> inputViews) throws CouchbaseLiteException {
        Log.e(TAG, "-------- updateIndexes() inputViews.size()="+inputViews.size()+", threadID="+Thread.currentThread().getName());
        for(ViewStore view:inputViews)
            Log.e(TAG, "updateIndexes() view="+view.getName());
        Log.e(TAG, "--------");

       ...
```

Following is log from test-case.
```
07-26 18:25:10.054 1529-1631/com.couchbase.liteservandroid V/View: Query test/basic: Found row with key=cbl_views_6, value=bar, id=cbl_views_6
07-26 18:25:10.054 1529-1673/com.couchbase.liteservandroid E/View: -------- updateIndexes() inputViews.size()=1, threadID=Acme.Utils.ThreadPool(4)-PooledThread: Acme.Serve.Serve$ServeConnection@b1e3d950
07-26 18:25:10.054 1529-1640/com.couchbase.liteservandroid E/View: -------- updateIndexes() inputViews.size()=1, threadID=Acme.Utils.ThreadPool(1)-PooledThread: Acme.Serve.Serve$ServeConnection@b1e373b8
07-26 18:25:10.064 1529-1673/com.couchbase.liteservandroid E/View: updateIndexes() view=test/basic
07-26 18:25:10.064 1529-1631/com.couchbase.liteservandroid V/View: Query test/basic: Found row with key=cbl_views_7, value=bar, id=cbl_views_7
07-26 18:25:10.064 1529-1640/com.couchbase.liteservandroid E/View: updateIndexes() view=test/basic
07-26 18:25:10.064 1529-1673/com.couchbase.liteservandroid E/View: --------
07-26 18:25:10.064 1529-1640/com.couchbase.liteservandroid E/View: --------
07-26 18:25:10.064 1529-1673/com.couchbase.liteservandroid I/cbforest: Database: beginTransaction
07-26 18:25:10.074 1529-1631/com.couchbase.liteservandroid V/View: Query test/basic: Found row with key=cbl_views_8, value=bar, id=cbl_views_8
07-26 18:25:10.084 1529-1673/com.couchbase.liteservandroid I/cbforest: Database: abort transaction
07-26 18:25:10.084 1529-1631/com.couchbase.liteservandroid V/View: Query test/basic: Found row with key=cbl_views_9, value=bar, id=cbl_views_9
07-26 18:25:10.084 1529-1640/com.couchbase.liteservandroid E/cbforest: Assertion failed: !_inTransaction (/Users/hideki/github/couchbase-lite-android-liteserv/libraries/couchbase-lite-java-forestdb/jni/../vendor/cbforest/CBForest/Database.cc:274, in void cbforest::Database::beginTransaction(cbforest::Transaction *))
07-26 18:25:10.094 1529-1673/com.couchbase.liteservandroid V/View: Query test/basic: Found row with key=cbl_views_0, value=bar, id=cbl_views_0
07-26 18:25:10.104 1529-1631/com.couchbase.liteservandroid V/Listener: RouterCallbackBlock.onResponseReady() START
07-26 18:25:10.104 1529-1631/com.couchbase.liteservandroid V/Listener: RouterCallbackBlock.onResponseReady() END
07-26 18:25:10.104 1529-1631/com.couchbase.liteservandroid V/Listener: CountDownLatch.await() START
07-26 18:25:10.104 1529-1631/com.couchbase.liteservandroid V/Listener: CountDownLatch.await() END
07-26 18:25:10.134 1529-1665/com.couchbase.liteservandroid E/ForestBridge: --------------->>>>>> ERROR: _err2status()
   com.couchbase.cbforest.ForestException: internal assertion failure
       at com.couchbase.cbforest.Indexer.beginIndex(Native Method)
       at com.couchbase.cbforest.Indexer.<init>(Indexer.java:25)
       at com.couchbase.lite.store.ForestDBViewStore.updateIndexes(ForestDBViewStore.java:254)
       at com.couchbase.lite.View.updateIndexes(View.java:321)
       at com.couchbase.lite.View.updateIndex(View.java:294)
       at com.couchbase.lite.router.Router.queryDesignDoc(Router.java:2403)
       at com.couchbase.lite.router.Router.do_GET_DesignDocument(Router.java:2435)
       at java.lang.reflect.Method.invokeNative(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.couchbase.lite.router.Router.start(Router.java:571)
       at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141)
       at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
       at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
       at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
       at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
       at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
       at java.lang.Thread.run(Thread.java:841)
07-26 18:25:10.154 1529-1673/com.couchbase.liteservandroid V/View: Query test/basic: Found row with key=cbl_views_1, value=bar, id=cbl_views_1
```

From log message, two threads (Two REST calls) executed updatedIndexes() method with view `test/basic` simultaneously.

**Comment by hideki** [comment]
Above case, just simply add `synchronized` keyword to `updateIndexes(...)` make solve

**Comment by hideki** [comment]
Other test case, two threads (`ThreadPool(4)` and `ThreadPool(0)`) calling `updateIndexes()` of different `ViewStore` instances (`b1efb8b0` and `b1dfc128`) with array of views (`test/basic`and `test/player`).

```
07-26 18:41:57.614 4185-4327/com.couchbase.liteservandroid E/View: -------- [com.couchbase.lite.store.ForestDBViewStore@b1efb8b0] updateIndexes() inputViews.size()=2, threadID=Acme.Utils.ThreadPool(4)-PooledThread: Acme.Serve.Serve$ServeConnection@b1dfc128
07-26 18:41:57.624 4185-4327/com.couchbase.liteservandroid E/View: updateIndexes() view=test/basic
07-26 18:41:57.624 4185-4327/com.couchbase.liteservandroid E/View: updateIndexes() view=test/player
07-26 18:41:57.624 4185-4327/com.couchbase.liteservandroid E/View: --------
07-26 18:41:57.664 4185-4291/com.couchbase.liteservandroid E/View: -------- [com.couchbase.lite.store.ForestDBViewStore@b1ef6778] updateIndexes() inputViews.size()=2, threadID=Acme.Utils.ThreadPool(0)-PooledThread: Acme.Serve.Serve$ServeConnection@b1dc9b48
07-26 18:41:57.674 4185-4291/com.couchbase.liteservandroid E/View: updateIndexes() view=test/basic
07-26 18:41:57.674 4185-4291/com.couchbase.liteservandroid E/View: updateIndexes() view=test/player
07-26 18:41:57.674 4185-4291/com.couchbase.liteservandroid E/View: --------
07-26 18:41:57.734 4185-4291/com.couchbase.liteservandroid I/cbforest: Database: beginTransaction
07-26 18:41:57.744 4185-4291/com.couchbase.liteservandroid E/cbforest: ForestDB handle is invalid (-30)
```

Logcat
```
07-26 18:41:57.614 4185-4327/com.couchbase.liteservandroid E/View: -------- [com.couchbase.lite.store.ForestDBViewStore@b1efb8b0] updateIndexes() inputViews.size()=2, threadID=Acme.Utils.ThreadPool(4)-PooledThread: Acme.Serve.Serve$ServeConnection@b1dfc128
07-26 18:41:57.624 4185-4327/com.couchbase.liteservandroid E/View: updateIndexes() view=test/basic
07-26 18:41:57.624 4185-4327/com.couchbase.liteservandroid E/View: updateIndexes() view=test/player
07-26 18:41:57.624 4185-4327/com.couchbase.liteservandroid E/View: --------
07-26 18:41:57.664 4185-4291/com.couchbase.liteservandroid E/View: -------- [com.couchbase.lite.store.ForestDBViewStore@b1ef6778] updateIndexes() inputViews.size()=2, threadID=Acme.Utils.ThreadPool(0)-PooledThread: Acme.Serve.Serve$ServeConnection@b1dc9b48
07-26 18:41:57.674 4185-4291/com.couchbase.liteservandroid E/View: updateIndexes() view=test/basic
07-26 18:41:57.674 4185-4291/com.couchbase.liteservandroid E/View: updateIndexes() view=test/player
07-26 18:41:57.674 4185-4291/com.couchbase.liteservandroid E/View: --------
07-26 18:41:57.734 4185-4291/com.couchbase.liteservandroid I/cbforest: Database: beginTransaction
07-26 18:41:57.744 4185-4291/com.couchbase.liteservandroid E/cbforest: ForestDB handle is invalid (-30)
07-26 18:41:57.744 4185-4291/com.couchbase.liteservandroid I/cbforest: Database: abort transaction
07-26 18:41:57.764 4185-4327/com.couchbase.liteservandroid I/cbforest: Database: beginTransaction
07-26 18:41:57.764 4185-4327/com.couchbase.liteservandroid I/cbforest: Database: beginTransaction
07-26 18:41:57.864 4185-4327/com.couchbase.liteservandroid D/dalvikvm: GC_FOR_ALLOC freed 368K, 9% free 4602K/5040K, paused 41ms, total 42ms
07-26 18:41:57.964 4185-4327/com.couchbase.liteservandroid E/View: Error in obj -> json
     com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class org.mozilla.javascript.Undefined and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) )
         at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:59)
         at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:26)
         at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:129)
         at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3383)
         at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:2801)
         at com.couchbase.lite.store.ForestDBViewStore$1.emit(ForestDBViewStore.java:342)
         at com.couchbase.lite.javascript.scopes.MapGlobalScope.emit(MapGlobalScope.java:39)
         at java.lang.reflect.Method.invokeNative(Native Method)
         at java.lang.reflect.Method.invoke(Method.java:515)
         at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
         at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:476)
         at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1701)
         at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:854)
         at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:164)
         at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:426)
         at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3178)
         at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:162)
         at com.couchbase.lite.javascript.ViewMapBlockRhino.map(ViewMapBlockRhino.java:66)
         at com.couchbase.lite.store.ForestDBViewStore.emit(ForestDBViewStore.java:334)
         at com.couchbase.lite.store.ForestDBViewStore.updateIndexes(ForestDBViewStore.java:300)
         at com.couchbase.lite.View.updateIndexes(View.java:321)
         at com.couchbase.lite.View.updateIndex(View.java:294)
         at com.couchbase.lite.router.Router.queryDesignDoc(Router.java:2403)
         at com.couchbase.lite.router.Router.do_GET_DesignDocument(Router.java:2435)
         at java.lang.reflect.Method.invokeNative(Native Method)
         at java.lang.reflect.Method.invoke(Method.java:515)
         at com.couchbase.lite.router.Router.start(Router.java:571)
         at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141)
         at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
         at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
         at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
         at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
         at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
         at java.lang.Thread.run(Thread.java:841)
07-26 18:41:57.974 4185-4327/com.couchbase.liteservandroid I/cbforest: **** update: realKey = [[2013,7,0],"cbl_views_0"]
07-26 18:41:57.974 4185-4327/com.couchbase.liteservandroid I/cbforest: DB 0xb87f6c58: added 070705409f74000000000005401c000000000000050000000000000000000633314507593f375b5307250000 --> 30 (meta 16) (seq 1)
07-26 18:41:57.974 4185-4327/com.couchbase.liteservandroid I/cbforest: DB 0xb87f6c58: added 0633314507593f375b53072500 --> 054105aea8000000000705409f74000000000005401c00000000000005000000000000000000 (meta ) (seq 2)
07-26 18:41:58.034 4185-4291/com.couchbase.liteservandroid E/ForestBridge: --------------->>>>>> ERROR: _err2status()
     com.couchbase.cbforest.ForestException: ForestDB handle is invalid
         at com.couchbase.cbforest.Indexer.beginIndex(Native Method)
         at com.couchbase.cbforest.Indexer.<init>(Indexer.java:25)
         at com.couchbase.lite.store.ForestDBViewStore.updateIndexes(ForestDBViewStore.java:254)
         at com.couchbase.lite.View.updateIndexes(View.java:321)
         at com.couchbase.lite.View.updateIndex(View.java:294)
         at com.couchbase.lite.router.Router.queryDesignDoc(Router.java:2403)
         at com.couchbase.lite.router.Router.do_GET_DesignDocument(Router.java:2435)
         at java.lang.reflect.Method.invokeNative(Native Method)
         at java.lang.reflect.Method.invoke(Method.java:515)
         at com.couchbase.lite.router.Router.start(Router.java:571)
         at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141)
         at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
         at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
         at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
         at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
         at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
         at java.lang.Thread.run(Thread.java:841)
07-26 18:41:58.034 4185-4291/com.couchbase.liteservandroid W/Router: Router unable to route request to do_GET_DesignDocument
   java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Method.invokeNative(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.couchbase.lite.router.Router.start(Router.java:571)
       at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141)
       at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
       at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
       at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
       at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
       at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
       at java.lang.Thread.run(Thread.java:841)
    Caused by: com.couchbase.lite.CouchbaseLiteException, Status: 590 (HTTP 500 Database error!)
       at com.couchbase.lite.store.ForestDBViewStore.updateIndexes(ForestDBViewStore.java:310)
       at com.couchbase.lite.View.updateIndexes(View.java:321)
       at com.couchbase.lite.View.updateIndex(View.java:294)
       at com.couchbase.lite.router.Router.queryDesignDoc(Router.java:2403)
       at com.couchbase.lite.router.Router.do_GET_DesignDocument(Router.java:2435)
       at java.lang.reflect.Method.invokeNative(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:515) 
       at com.couchbase.lite.router.Router.start(Router.java:571) 
       at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141) 
       at javax.servlet.http.HttpServlet.service(HttpServlet.java:802) 
       at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251) 
       at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176) 
       at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988) 
       at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223) 
       at java.lang.Thread.run(Thread.java:841) 
07-26 18:41:58.034 4185-4291/com.couchbase.liteservandroid V/Listener: RouterCallbackBlock.onResponseReady() START
07-26 18:41:58.044 4185-4291/com.couchbase.liteservandroid V/Listener: RouterCallbackBlock.onResponseReady() END
```

**Comment by NitzDKoder** [comment]
@hideki  is this same as ?
https://github.com/couchbase/couchbase-lite-java-core/issues/1535

Any hot fix available? pls confirm..

**Comment by hideki** [comment]
@NitzDKoder, v1.4.0 will be released soon.

**Comment by cilvet** [comment]
this is still happening to me while trying to use this [photo-drop app](https://github.com/couchbaselabs/photo-drop/tree/master/android) on android

Logcat
`Router unable to route request to do_PUT_Document
                                                                     java.lang.reflect.InvocationTargetException
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.couchbase.lite.router.Router.start(Router.java:560)
                                                                         at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:147)
                                                                         at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
                                                                         at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2408)
                                                                         at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2330)
                                                                         at Acme.Serve.Serve$ServeConnection.run(Serve.java:2110)
                                                                         at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1238)
                                                                         at java.lang.Thread.run(Thread.java:818)
                                                                      Caused by: com.couchbase.lite.CouchbaseLiteException, Status: 406 (HTTP 406 not_acceptable)
                                                                         at com.couchbase.lite.router.Router.getBodyAsDictionary(Router.java:247)
                                                                         at com.couchbase.lite.router.Router.do_PUT_Document(Router.java:2364)
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                         at com.couchbase.lite.router.Router.start(Router.java:560) 
                                                                         at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:147) 
                                                                         at javax.servlet.http.HttpServlet.service(HttpServlet.java:802) 
                                                                         at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2408) 
                                                                         at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2330) 
                                                                         at Acme.Serve.Serve$ServeConnection.run(Serve.java:2110) 
                                                                         at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1238) 
                                                                         at java.lang.Thread.run(Thread.java:818) `

**Comment by hideki** [comment]
@cilvet Thank you for your report.

**Comment by hideki** [comment]
Task: Test CBL Android 1.4.0 library with Photo-Drop. And confirm if this issue is still reproducible. https://github.com/couchbaselabs/photo-drop/issues/15

**Comment by hideki** [comment]
The original issue which was reproducible with functional test environment was fixed. 
Symptoms are same, but root causes are different. To isolate the original problem with Photo drop issue, I created following ticket. I will track the issue with i.
https://github.com/couchbase/couchbase-lite-java-core/issues/1660
