### ISSUE TITLE
Crash while building/rebuiding View

### ISSUE THREAD

**Issue by jcamp1** [couchbase/couchbase-lite-java-core#497]
Greetings,

On my Galaxy S2 I am receiving the following crash consistently:
```
03-16 11:53:52.488  20863-20975/com.app.appmobile.alpha W/CursorWindow﹕ Window is full: requested allocation 39055 bytes, free space 4069 bytes, window size 2097152 bytes
03-16 11:53:54.450  20863-20975/com.app.appmobile.alpha W/CursorWindow﹕ Window is full: requested allocation 39055 bytes, free space 621 bytes, window size 2097152 bytes
03-16 11:53:54.781  20863-20975/com.app.appmobile.alpha W/CursorWindow﹕ Window is full: requested allocation 39055 bytes, free space 10177 bytes, window size 2097152 bytes
03-16 11:53:54.791  20863-20975/com.app.appmobile.alpha E/CursorWindow﹕ Failed to read row 486, column 0 from a CursorWindow which has 486 rows, 7 columns.
03-16 11:53:54.791  20863-20975/com.app.appmobile.alpha W/View﹕ Failed to rebuild view users.  Result code: 500
03-16 11:53:54.791  20863-20975/com.app.appmobile.alpha I/CBLite﹕ CBLManagerWorkExecutor CANCEL transaction (level 0)
03-16 11:53:54.821  20863-20975/com.app.appmobile.alpha E/Sync﹕ Exception calling changeListener.changed
    java.lang.IllegalStateException: Couldn't read row 486, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
            at android.database.CursorWindow.nativeGetLong(Native Method)
            at android.database.CursorWindow.getLong(CursorWindow.java:511)
            at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
            at com.couchbase.lite.android.AndroidSQLiteStorageEngine$SQLiteCursorWrapper.getLong(AndroidSQLiteStorageEngine.java:198)
            at com.couchbase.lite.View.updateIndex(View.java:543)
            at com.couchbase.lite.Database.queryViewNamed(Database.java:2204)
            at com.couchbase.lite.Query.run(Query.java:395)
            at com.app.applib.model.user.User.getUser(User.java:55)
            at com.app.appmobile.AppEngine.SyncComplete(AppEngine.java:162)
            at com.app.applib.network.Sync.evaluateSessionStatus(Sync.java:304)
            at com.app.applib.network.Sync.changed(Sync.java:243)
            at com.couchbase.lite.replicator.Replication.changed(Replication.java:357)
            at com.couchbase.lite.replicator.ReplicationInternal$10.run(ReplicationInternal.java:1028)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
            at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
            at java.util.concurrent.FutureTask.run(FutureTask.java:137)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
            at java.lang.Thread.run(Thread.java:856)
```

I've tried a simple background looper waiting until view.isStale() is false before utilizing the view query, but view.isStale() always returns true and the lastSequenceIndexed() is always zero.

The view is as follows:
```
public void createUsersView() {
        if (database == null) { return; }
        View view = database.getView("users");
        Mapper mapper = new Mapper() {
            @Override
            public void map(Map<String, Object> doc, Emitter emitter) {
                if (doc.get("type") != null && doc.get("type").equals("user")) {
                    emitter.emit(doc.get("name"), doc.get("locationRoot"));
                }
            }
        };
        view.setMap(mapper, "1.0");
        usersQuery = view.createQuery();
    }
```

On an emulator I am *not* receiving this error or crashing, so I'm guessing it has something to do with this device's slower processor or something hardware related.

Thanks,
Justin

**Comment by tleyden** [comment]
On the surface, looks like a duplicate of https://github.com/couchbase/couchbase-lite-android/issues/256

If not, let me know and I'll re-open it.

**Comment by hideki** [comment]
@jcamp1 and @tleyden,

I guess many of  `CursorWindow` related issues could be caused by limited memory. 

S2 is 1GB device, and 24MB is available per application. Some of @jcamp1 's document size is around 100KB.

`View.updateIndex()` might be required to optimize memory usage. This also could make `View.updateIndex()` slower by GC.

**Comment by hideki** [comment]
Hi @jcamp1
Can you provide followings if you can?
- Can you use "Memory Monitor" feature of Android Studio to measure over all memory usage during `View.updateIndex()`? 
-  Also, if possible, can you use "Android Device Monitor" to capture memory snap shot before crash occurs? "Dump HPROF File" command?
Thanks!

**Comment by jcamp1** [comment]
Hi @hideki,

This ticket was closed by @tleyden. Should we move our discussions over to #256?

**Comment by hideki** [comment]
Hi @jcamp1 ,

If the document (JSON string) size is larger than 2MB, we can not fix the issue because of SQLite limitation on Android. It is https://github.com/couchbase/couchbase-lite-android/issues/256. Please confirm your document size.

If your document is smaller than 2MB, it is not same issue with couchbase/couchbase-lite-android/issues/256. Please reopen this ticket by clicking "Reopen and comment" button at bottom of this page.

**Comment by tleyden** [comment]
I'm re-opening it.

**Comment by jcamp1** [comment]
Hmm, well it can't be that issue because the problem I'm seeing is only happening on the S2. The emulator and a Razr M we have here at the office both work. If it's a general android SQLite issue then it couldn't be related to #256.

**Comment by hideki** [comment]
@jcamp1  Are you using same documents that I can access from your sync_gateway? If so, I will try to reproduce this issue here.

**Comment by jcamp1** [comment]
Give me a couple minutes to verify the user we gave you is getting the same issues pls.

**Comment by jcamp1** [comment]
Just completed the test on the user/pass I gave you. It's a different subset of data so it's not occurring. I will email you with the username/pass of the account that is having this issue.

Cheers!
Justin

**Comment by hideki** [comment]
Hi @jcamp1,
I did not look into the issue yet. But recently we fixed the bottle neck of `View.updateIndex()` performance issue. #502, #500. It might fix your issue too.
If you have time, could you please test your code with  master branch?
Both couchbase-lite-android and couchbase-lite-java-core should be latest on master.
Thanks,
Hideki

**Comment by jcamp1** [comment]
I will do so and report back, thanks!

**Comment by jcamp1** [comment]
Greetings @hideki,

I have tested the latest code and verified that, unfortunately, the issue is not resolved.

Cheers,
Justin

**Comment by hideki** [comment]
Hi @jcamp1, Thank you very much for your help. We will look into the issue as soon as possible.

**Comment by hideki** [comment]
Log Message

Android Standard Emulator with x86, 1G memory, API 16 configuration
```
3-23 16:40:30.541    1549-1549/self.hideki.issue497 E/CursorWindow﹕ Failed to read row 151, column 0 from a CursorWindow which has 151 rows, 7 columns.
03-23 16:40:30.541    1549-1549/self.hideki.issue497 W/View﹕ Failed to rebuild view users.  Result code: 500
03-23 16:40:30.541    1549-1549/self.hideki.issue497 D/AndroidRuntime﹕ Shutting down VM
03-23 16:40:30.541    1549-1549/self.hideki.issue497 W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0xb2e28288)
03-23 16:40:30.541    1549-1549/self.hideki.issue497 E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.IllegalStateException: Could not execute method of the activity
            at android.view.View$1.onClick(View.java:3591)
            at android.view.View.performClick(View.java:4084)
            at android.view.View$PerformClick.run(View.java:16966)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at android.view.View$1.onClick(View.java:3586)
            at android.view.View.performClick(View.java:4084)
            at android.view.View$PerformClick.run(View.java:16966)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalStateException: Couldn't read row 151, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
            at android.database.CursorWindow.nativeGetLong(Native Method)
            at android.database.CursorWindow.getLong(CursorWindow.java:507)
            at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
            at com.couchbase.lite.android.AndroidSQLiteStorageEngine$SQLiteCursorWrapper.getLong(AndroidSQLiteStorageEngine.java:215)
            at com.couchbase.lite.View.updateIndex(View.java:541)
            at com.couchbase.lite.Database.queryViewNamed(Database.java:2228)
            at com.couchbase.lite.Query.run(Query.java:395)
            at self.hideki.issue497.Application.iterateQuery(Application.java:95)
            at self.hideki.issue497.MainActivity.iterateQuery(MainActivity.java:62)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at android.view.View$1.onClick(View.java:3586)
            at android.view.View.performClick(View.java:4084)
            at android.view.View$PerformClick.run(View.java:16966)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)

```

**Comment by hideki** [comment]
Another Log from Android Xoom 1GB memory device
```
03-23 16:56:04.810  15411-15411/self.hideki.issue497 E/Issue447﹕ iterateQuery() is clicked
03-23 16:56:05.060  15411-15411/self.hideki.issue497 W/CursorWindow﹕ Window is full: requested allocation 40496 bytes, free space 21077 bytes, window size 2097152 bytes
03-23 16:56:05.300  15411-15415/self.hideki.issue497 D/dalvikvm﹕ GC_CONCURRENT freed 1044K, 73% free 8221K/29383K, paused 12ms+9ms, total 67ms
03-23 16:56:05.300  15411-15411/self.hideki.issue497 D/dalvikvm﹕ WAIT_FOR_CONCURRENT_GC blocked 26ms
03-23 16:56:05.460  15411-15415/self.hideki.issue497 D/dalvikvm﹕ GC_CONCURRENT freed 817K, 73% free 8153K/29383K, paused 3ms+6ms, total 48ms
03-23 16:56:05.460  15411-15411/self.hideki.issue497 D/dalvikvm﹕ WAIT_FOR_CONCURRENT_GC blocked 23ms
03-23 16:56:05.580  15411-15415/self.hideki.issue497 D/dalvikvm﹕ GC_CONCURRENT freed 626K, 72% free 8253K/29383K, paused 2ms+6ms, total 44ms
03-23 16:56:05.580  15411-15411/self.hideki.issue497 D/dalvikvm﹕ WAIT_FOR_CONCURRENT_GC blocked 33ms
03-23 16:56:05.790  15411-15411/self.hideki.issue497 W/CursorWindow﹕ Window is full: requested allocation 40336 bytes, free space 25417 bytes, window size 2097152 bytes
03-23 16:56:05.960  15411-15411/self.hideki.issue497 W/CursorWindow﹕ Window is full: requested allocation 40336 bytes, free space 27721 bytes, window size 2097152 bytes
03-23 16:56:05.960  15411-15411/self.hideki.issue497 E/CursorWindow﹕ Failed to read row 151, column 0 from a CursorWindow which has 151 rows, 7 columns.
03-23 16:56:05.960  15411-15411/self.hideki.issue497 W/View﹕ Failed to rebuild view users.  Result code: 500
03-23 16:56:05.970  15411-15411/self.hideki.issue497 D/AndroidRuntime﹕ Shutting down VM
03-23 16:56:05.970  15411-15411/self.hideki.issue497 W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41de3300)
03-23 16:56:05.990  15411-15411/self.hideki.issue497 E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.IllegalStateException: Could not execute method of the activity
            at android.view.View$1.onClick(View.java:3591)
            at android.view.View.performClick(View.java:4084)
            at android.view.View$PerformClick.run(View.java:16966)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at android.view.View$1.onClick(View.java:3586)
            at android.view.View.performClick(View.java:4084)
            at android.view.View$PerformClick.run(View.java:16966)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalStateException: Couldn't read row 151, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
            at android.database.CursorWindow.nativeGetLong(Native Method)
            at android.database.CursorWindow.getLong(CursorWindow.java:507)
            at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
            at com.couchbase.lite.android.AndroidSQLiteStorageEngine$SQLiteCursorWrapper.getLong(AndroidSQLiteStorageEngine.java:215)
            at com.couchbase.lite.View.updateIndex(View.java:541)
            at com.couchbase.lite.Database.queryViewNamed(Database.java:2228)
            at com.couchbase.lite.Query.run(Query.java:395)
            at self.hideki.issue497.Application.iterateQuery(Application.java:95)
            at self.hideki.issue497.MainActivity.iterateQuery(MainActivity.java:62)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at android.view.View$1.onClick(View.java:3586)
            at android.view.View.performClick(View.java:4084)
            at android.view.View$PerformClick.run(View.java:16966)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by hideki** [comment]
[calling View.updateIndex() on a database containing big json documents crashes on certain devices](https://github.com/couchbase/couchbase-lite-android/issues/210). It seems this is same issue.

**Comment by hideki** [comment]
Note to self:

##### so far I knew
1. This issue could be caused by older version of SQLite (Older Android API) : API 16 => Issue, API 21 => No Issue
1. As logs tell, the IllegalStateException is thrown from `Cursor.getLong()`
1. According to the java doc, `Cursor.getLong()` throws Exception if column is null. http://developer.android.com/reference/android/database/Cursor.html#getLong(int)
1. Useful blog about getLong() => http://blog.tapreason.com/2014/03/02/how-to-resolve-java-lang-illegalstateexception-couldnt-read-row-0-col-y-from-cursorwindow-make-sure-the-cursor-is-initialized-correctly-before-accessing-data-from-it/
1. The solution which is described in above blog, calling `Cursor.isNull()` to check null and returning default value, does cause different Query Iteration results, compared with latest Android version.

##### Next Step:
1. Compare SQLite Databases between created by old Android SDK and latest Android SDK.
1. Check SQL which causes problem
1. Handle IllegalStateException, and skip that query result.

**Comment by hideki** [comment]
Hi @jcamp1,

We fixed the issue, and changes are already merged into master branch. Could you please verify the fix? I have one request. When you test it, could you please also check query results? Query results should be same with previous version of CBL Android on latest device (which does not cause this issue).

Thanks!
Hideki

**Comment by jcamp1** [comment]
Hi @hideki,

Sorry for the late response, work has been really busy as of late. I will test this asap and get back to you.

Cheers,
Justin

**Comment by jcamp1** [comment]
hi @hideki,

This is confirmed to be fixed on the device I was having issues with.

Thanks so much!
Justin

**Comment by hideki** [comment]
Hi @jcamp1,

Thank you very much for verifying the fix, and also sharing your data that helped a lot to understand the problem.

Did you have a chance to read my comment for #456 ?

Cheers!
Hideki
