### ISSUE TITLE
Document.update (new Document.DocumentUpdater() - java.lang.NullPointerException

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#693]
This is copied from forums.couchbase.com
https://forums.couchbase.com/t/document-update-new-document-documentupdater-java-lang-nullpointerexception/4412

Version
com.couchbase.lite:couchbase-lite-android:1.0.4

Hello everyone,

I am facing an issue, which produces a crash of the app.

Scenario :

-MainActivity.OnCreate : My app create a doc with a push/pull continous replication.
Doc is created in CBLite and in CouchServers too.
-MainActivity.OnCreate : My app add and attachment (picture) to the newly created doc.
-MainActivity.BroadcastReceiver : My app receive an intent with new data, and i then call the code to update the document with some of these data.

-CRASH ! nullPointerException on "document.update(new Document.DocumentUpdater()"

I check the value of "document" just before in my logcat and is is not null.

If i restart the application (2nd launch)... no crash...everything is ok.
If i remove the step to add the attachment (picture)...everything is ok even at first launch

Is it possible that the BroadcastReceiver uses a different thread that the one used by the DocumentUpdater ?
I dont understand the error...could anyone explain me the cause and how to solve it ?

Best regards @ Couchbase's community !

Function
```java
private void updateProfileLocation(Database database, String documentId) {

   String data = readFromFile(fileNameUserProfileData); 
   JSONObject jsonObj = null;             
   JSONObject subObj = null;

try {
    jsonObj = new JSONObject(data);              
    subObj = jsonObj.getJSONObject("userinfo"); 
} catch (JSONException e1) {
    e1.printStackTrace();
}
        try {
            final String mLastUpdateTime= subObj.getString("mLastUpdateTime");
            Document document = database.getDocument(documentId);

            document.update(new Document.DocumentUpdater() {
                // Update the document with more data
                @Override
                public boolean update(UnsavedRevision newRevision) {
                    Map<String, Object> properties = newRevision.getUserProperties();
                    properties.put("lastUpdateTime", mLastUpdateTime);      //
                    newRevision.setUserProperties(properties);
                    return true;
                }
            });
        } catch (CouchbaseLiteException | JSONException e) {
            e.printStackTrace();
        }
```
**Logs **
```
07-07 01:15:29.064  12114-12114/com.xxxxxxx.xxxxxxW/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41744c68)
    07-07 01:15:29.064  12114-12114/com.xxxxxx.xxxxxxE/AndroidRuntime﹕ FATAL EXCEPTION: main
        Process: com.appinmotion.truemeet, PID: 12114
        java.lang.NullPointerException
                at com.couchbase.lite.Database.generateIDForRevision(Database.java:3223)
                at com.couchbase.lite.Database.putRevision(Database.java:3622)
                at com.couchbase.lite.Database.putRevision(Database.java:3465)
                at com.couchbase.lite.Document.putProperties(Document.java:415)
                at com.couchbase.lite.UnsavedRevision.save(UnsavedRevision.java:102)
                at com.couchbase.lite.Document.update(Document.java:275)
                at com.xxxx.xxxx.MainActivity.updateProfileLocation(MainActivity.java:803)
                at com.xxxxx.xxxxx.MainActivity.access$1000(MainActivity.java:158)
                at com.xxxxx.xxxxxx.MainActivity$4.onReceive(MainActivity.java:446)
                at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
                at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
                at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
                at android.os.Handler.dispatchMessage(Handler.java:102)
                at android.os.Looper.loop(Looper.java:136)
                at android.app.ActivityThread.main(ActivityThread.java:5081)
                at java.lang.reflect.Method.invokeNative(Native Method)
                at java.lang.reflect.Method.invoke(Method.java:515)
                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
                at dalvik.system.NativeStart.main(Native Method)
    07-07 01:17:09.251  12114-12271/com.xxxxx.xxxxxW/Sync﹕ com.couchbase.lite.replicator.PullerInternal@42123540 no new remote revisions to fetch.  add lastInboxSequence (5) to pendingSequences (com.couchbase.lite.support.SequenceMap@42173630)
```

Here is my code for uploading the attachment :
```java


    private class UploadPictureTask extends AsyncTask {

    @Override
    protected Double doInBackground(File...params) {

    Document document = database.getDocument(userId);

    if(document != null)
    { /* BEGIN  : Save Picture to Database */

        try {
            ContextWrapper cw = new ContextWrapper(getApplicationContext());
            File pictureLocation = cw.getDir("imageDir", Context.MODE_PRIVATE); // path to /data/data/yourapp/app_data/imageDir
            File picture1=new File(pictureLocation, MainActivity.fileNamePicture1 + ".jpg");
            File picture2=new File(pictureLocation, MainActivity.fileNamePicture2 + ".jpg");
            File picture3=new File(pictureLocation, MainActivity.fileNamePicture3 + ".jpg");
            InputStream stream = new FileInputStream(picture1);

            // Add or update an image to a document as a JPEG attachment:
            Document doc = database.getDocument(userId);

            UnsavedRevision newRev = doc.getCurrentRevision().createRevision();
            newRev.setAttachment(fileNamePicture1 + ".jpg", "image/jpeg", stream);
            if (picture2.exists())
            {
                InputStream stream2 = new FileInputStream(picture2);
                newRev.setAttachment(fileNamePicture2 + ".jpg", "image/jpeg", stream2);
            }
            if (picture3.exists())
            {
                InputStream stream3 = new FileInputStream(picture3);
                newRev.setAttachment(fileNamePicture3 + ".jpg", "image/jpeg", stream3);
            }
            newRev.save();
        }  catch (FileNotFoundException | CouchbaseLiteException e) {
            e.printStackTrace();
        }
    }/* CLOSE  : Save Picture to Database */
        return null;
    }

```

**Comment by hideki** [comment]
Additional information from user

Unfortunately, i won't be able to provide you a sample application.

But this scenario is easily reproducible

I just re-tried it :

i take a picture with the phone (in my app, an intent trigger the camera)
I save file locally on the phone
I call the method UploadPictureTask that i provided you earlier
Then i got the crash with the following exception:

```
07-28 15:44:05.914 1467-1467/com.xxxxxxxx.xxxxxxE/AndroidRuntime﹕ FATAL EXCEPTION: main
Process: com.xxxxx.xxxxx, PID: 1467
java.lang.RuntimeException: Unable to read from stream.
at com.couchbase.lite.BlobStoreWriter.read(BlobStoreWriter.java:94)
at com.couchbase.lite.Attachment.blobStoreWriterForBody(Attachment.java:214)
at com.couchbase.lite.Attachment.installAttachmentBodies(Attachment.java:193)
at com.couchbase.lite.Document.putProperties(Document.java:402)
at com.couchbase.lite.UnsavedRevision.save(UnsavedRevision.java:102)
at com.couchbase.lite.Document.update(Document.java:275)
at com.xxxxx.xxxxx.MainActivity.updateProfileLocationinDB(MainActivity.java:778)
at com.xxxxx.xxxxx.MainActivity.access$900(MainActivity.java:159)
at com.xxxxx.xxxxx.MainActivity$4.onReceive(MainActivity.java:450)
at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5081)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.io.IOException: read failed: EBADF (Bad file number)
at libcore.io.IoBridge.read(IoBridge.java:435)
at java.io.FileInputStream.read(FileInputStream.java:179)
at java.io.InputStream.read(InputStream.java:162)
at com.couchbase.lite.BlobStoreWriter.read(BlobStoreWriter.java:87)
at com.couchbase.lite.Attachment.blobStoreWriterForBody(Attachment.java:214)
at com.couchbase.lite.Attachment.installAttachmentBodies(Attachment.java:193)
at com.couchbase.lite.Document.putProperties(Document.java:402)
at com.couchbase.lite.UnsavedRevision.save(UnsavedRevision.java:102)
at com.couchbase.lite.Document.update(Document.java:275)
at com.xxxxx.xxxxx.MainActivity.updateProfileLocationinDB(MainActivity.java:778)
at com.xxxxx.xxxxx.MainActivity.access$900(MainActivity.java:159)
at com.xxxxx.xxxxx.MainActivity$4.onReceive(MainActivity.java:450)
at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5081)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
at dalvik.system.NativeStart.main(Native Method)
Caused by: libcore.io.ErrnoException: read failed: EBADF (Bad file number)
at libcore.io.Posix.readBytes(Native Method)
at libcore.io.Posix.read(Posix.java:128)
at libcore.io.BlockGuardOs.read(BlockGuardOs.java:149)
at libcore.io.IoBridge.read(IoBridge.java:425)
at java.io.FileInputStream.read(FileInputStream.java:179)
at java.io.InputStream.read(InputStream.java:162)
at com.couchbase.lite.BlobStoreWriter.read(BlobStoreWriter.java:87)
at com.couchbase.lite.Attachment.blobStoreWriterForBody(Attachment.java:214)
at com.couchbase.lite.Attachment.installAttachmentBodies(Attachment.java:193)
at com.couchbase.lite.Document.putProperties(Document.java:402)
at com.couchbase.lite.UnsavedRevision.save(UnsavedRevision.java:102)
at com.couchbase.lite.Document.update(Document.java:275)
at com.xxxxx.xxxxx.MainActivity.updateProfileLocationinDB(MainActivity.java:778)
at com.xxxxx.xxxxx.MainActivity.access$900(MainActivity.java:159)
at com.xxxxx.xxxxx.MainActivity$4.onReceive(MainActivity.java:450)
at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5081)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
at dalvik.system.NativeStart.main(Native Method)
07-28 15:44:22.150 1467-1696/com.xxxxx.xxxxx W/Sync﹕ com.couchbase.lite.replicator.PullerInternal@428a0f28 no new remote revisions to fetch. add lastInboxSequence (3087) to pendingSequences (com.couchbase.lite.support.SequenceMap@429e05f0)
```

------
5.After that, when i relaunch the app, the "UpdateProfileLocation" executes successfully 3-4 times then the app crashes again with the following exception :

```
07-28 15:54:14.818 1541-1541/com.xxxxx.xxxxx D/AndroidRuntime﹕ Shutting down VM
07-28 15:54:14.818 1541-1541/com.xxxxx.xxxxx W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41becc68)
07-28 15:54:14.848 1541-1541/com.xxxxx.xxxxx E/AndroidRuntime﹕ FATAL EXCEPTION: main
Process: com.xxxxx.xxxxx, PID: 1541
java.lang.NullPointerException
at com.couchbase.lite.Database.generateIDForRevision(Database.java:3223)
at com.couchbase.lite.Database.putRevision(Database.java:3622)
at com.couchbase.lite.Database.putRevision(Database.java:3465)
at com.couchbase.lite.Document.putProperties(Document.java:415)
at com.couchbase.lite.UnsavedRevision.save(UnsavedRevision.java:102)
at com.couchbase.lite.Document.update(Document.java:275)
at com.xxxxx.xxxxx.MainActivity.updateProfileLocationinDB(MainActivity.java:778)
at com.xxxxx.xxxxx.MainActivity.access$900(MainActivity.java:159)
at com.xxxxx.xxxxx.MainActivity$4.onReceive(MainActivity.java:450)
at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5081)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
at dalvik.system.NativeStart.main(Native Method)
07-28 15:55:16.848 1541-1762/com.xxxxx.xxxxx W/Sync﹕ com.couchbase.lite.replicator.PullerInternal@42312fb0 no new remote revisions to fetch. add lastInboxSequence (3113) to pendingSequences (com.couchbase.lite.support.SequenceMap@42306be0)
```

6. Another important point is that attachment are uploaded to CouchServer. So, anyhow, it worked once and attachment were uploaded...

I will try to retry this on a clean device/install, and check if, depite of exceptions, attachment is uploaded or not.

**Comment by hideki** [comment]
Currently we are working with Couchbase Forum.  Temporary I will close this ticket.

**Comment by heretyk** [comment]
So the issue still happens.

Basically, we upload an attachment via an AsyncTask (code above).

The revision arrives to servers and the attachment is correctly saved.

But no more revision can be done until app is restarted = so i guess that closing the CBlite local databate and manager "solve" the issue.

**Comment by heretyk** [comment]
Just made the test on a fresh new install and new Document.

Attachment is correctly uploaded to server, but then i cannot make further revision to this doc.
Each time my app try to update/create a property inside this doc, i see this in Logs :  

09-11 04:38:03.812    5338-5338/net.xxxxxx W/CBLite﹕ No pending attachment for digest: sha1-ehQGklBAAWfrBLR/a0vnzt8+ErA=
09-11 04:38:08.922    5338-5338/net.xxxxxx W/CBLite﹕ No pending attachment for digest: sha1-ehQGklBAAWfrBLR/a0vnzt8+ErA=
09-11 04:38:13.962    5338-5338/net.xxxxxx W/CBLite﹕ No pending attachment for digest: sha1-ehQGklBAAWfrBLR/a0vnzt8+ErA=
09-11 04:38:18.972    5338-5338/net.xxxxxx W/CBLite﹕ No pending attachment for digest: sha1-ehQGklBAAWfrBLR/a0vnzt8+ErA=
09-11 04:38:23.892    5338-5338/net.xxxxxx W/CBLite﹕ No pending attachment for digest: sha1-ehQGklBAAWfrBLR/a0vnzt8+ErA=

**Comment by heretyk** [comment]
Is it normal that the channels property of my doc is like that in Database too : 

"
{
   "_attachments": {
       "picture1.jpg": {
           "content_type": "image/jpeg",
           "digest": "sha1-ehQGklBAAWfrBLR/a0vnzt8+ErA=",
           "length": 442327,
           "revpos": 8,
           "stub": true
       }
   },
   "_sync": {
       "rev": "8-c6b07d5eb4544c9273d4e9a269b8fb80",
       "sequence": 103588,
       "recent_sequences": [
           103584,
           103585,
           103586,
           103587,
           103588
       ],
       "history": {
           "revs": [
               "8-c6b07d5eb4544c9273d4e9a269b8fb80",
               "2-e78d0482d57b98d91e310eb40626b661",
               "3-bb3c1cbf91449bea18b93bf25488d158",
               "4-d42336c83920cc0bb45d8a4dae981bd6",
               "5-922b5936bc72408d9b065b05a45bca54",
               "1-48a490b49bd23dd1544a56522279c289",
               "6-d20c133f489dc66bf95976756be0c261",
               "7-59ab506c03ff0c3eb3da111c8b141921"
           ],
           "parents": [
               7,
               5,
               1,
               2,
               3,
               -1,
               4,
               6
           ],
           "bodies": [
               "",
               "",
               "",
               "",
               "",
               "",
               "",
               ""
           ],
           "channels": [
               [
                   "profile"
               ],
               null,
               null,
               [
                   "profile"
               ],
               [
                   "profile"
               ],
               null,
               [
                   "profile"
               ],
               [
                   "profile"
               ]
           ]
       },

.....
.....


"

**Comment by jackwang1** [comment]
We are also seeing this issue exactly, using couchbase lite 1.1.0 on android. As in:
1. Create doc, add attachment -  works and content gets synced
2. Modify doc to add field - exception below

Same code works when sync is turned off or device is offline.

    W/CBLite﹕ No pending attachment for digest: sha1-AfySsHsKpUtOSxK29Ja1C7iiiew=

    com.couchbase.lite.CouchbaseLiteException
            at com.couchbase.lite.Database.installAttachment(Database.java:2948)
            at com.couchbase.lite.Database.getAttachmentsFromRevision(Database.java:4285)
            at com.couchbase.lite.Database.putRevision(Database.java:4063)
            at com.couchbase.lite.Database.putRevision(Database.java:3923)
            at com.couchbase.lite.Document.putProperties(Document.java:420)
            at com.couchbase.lite.Document.putProperties(Document.java:252)
            ...
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5074)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by jackwang1** [comment]
Previous correspondence asked for code, here's an android app where the problem can be easily reproduced.

https://github.com/jackwang1/CouchbaseSyncTest

**Comment by hideki** [comment]
Hi @jackwang1, Thank you very much for test codes.

**Comment by heretyk** [comment]
Hi @jackwang1, Thanks for you participation.

"Glad" to know that i am not alone to experience this...

@hideki : Two more informations i noticed :+1: 

1. I monitored in the gateway, and nothing is logged since the exact time that the attachment is saved to the doc. Replication is actually stopped between mobile device and Couch GW.

2. I managed to handle conflict; merging revision after obtaining conflict with 'document.getConflictingRevisions();'. I can confirm that after the attachment, the document is not in conflict.

I am looking forward to hear news from you.

Please give me a feedback as soon as you identify the cause of this issues, and even better, if you can give a workaround; or a date for a "fix" (if needed).

It is the last issue we have to solve before last testing phase of our App before launch.

Regards

**Comment by hideki** [comment]
Hi @jackwang1 ,
I tried to reproduce the issue with your sample and following your instruction in README . However I could not reproduce the problem. `bookmark` field is correctly toggled.I am using Sync Gateway v1.1.0 and  Couchbase Server 2.2.0. And test run on Genymotion with API 19 (Android 4.4.4). Please share if there is tips to reproduce the problem.
Thanks,
Hideki

**Comment by jackwang1** [comment]
We are running sync gateway v1.0.2-9 (commit 95ef60ab), and couchbase
server 4.0.0-4047. We found an existing AWS AMI, but can update to any
version.

Also, I've seen the sync work the first run of the app. Try closing,
opening and clicking the button a few times.

Thanks,
Jack

**Comment by hideki** [comment]
Hi @jackwang1,
Thanks for your advice. I will try again.
We have many fixes in Sync Gateway v1.1.0. I recommend to use v1.1.0.
Thanks,
Hideki

**Comment by heretyk** [comment]
Hello,

I am on 1.1.0, i upgraded 1 months ago while i was already experiencing the
issue.

It didn't solve the issue.

2015-09-25 2:57 GMT+02:00 Hideki Itakura <notifications@github.com>:

**Comment by heretyk** [comment]
@hideki , @zgramana : 

Hello,

Can you provide some feedback on this issue ? 
Did you identify the causes and find a solution ?
When will be able to upload attachments ?

This is the last issue in our backlog so that we can use the app in production.

Regards,

**Comment by francescopedronomnys** [comment]
Hello,
using couchbase-lite-android:1.1.0 and I'm seeing the attached exception too.
It looks like this exception is thrown when I insert a "big" attachment (a JPG) into the document and then I try to update a property.
If I change the attachment with a smaller one on the same document I'm then able to change the property successfully.

Regards,
Francesco

>10-19 11:20:41.384 13572-13572/redacted W/CBLite: No pending attachment for digest: sha1-rXWsIRu2eQcuo3HORuKqp12oFYw=
>10-19 11:20:41.384 13572-13572/redacted V/Database: main CANCEL transaction (level 0)
>10-19 11:20:41.384 13572-13572/redacted W/System.err: com.couchbase.lite.CouchbaseLiteException
>10-19 11:20:41.389 13572-13572/redacted W/System.err:     at com.couchbase.lite.Database.installAttachment(Database.java:2948)
>10-19 11:20:41.389 13572-13572/redacted W/System.err:     at com.couchbase.lite.Database.getAttachmentsFromRevision(Database.java:4285)
>10-19 11:20:41.389 13572-13572/redacted W/System.err:     at com.couchbase.lite.Database.putRevision(Database.java:4063)
>10-19 11:20:41.389 13572-13572/redacted W/System.err:     at com.couchbase.lite.Database.putRevision(Database.java:3923)
>10-19 11:20:41.389 13572-13572/redacted W/System.err:     at com.couchbase.lite.Document.putProperties(Document.java:420)
>10-19 11:20:41.389 13572-13572/redacted W/System.err:     at com.couchbase.lite.Document.putProperties(Document.java:252)

**Comment by zgramana** [comment]
@jackwang1 The repo code you linked to above is very helpful. Not only was I able to reproduce your problem, but I've included the revised code below. There isn't a a bug in the code when it's used as intended, but it's one part of our API that is confusing and that we have plans to address.

The canonical way to do this is:
```diff
     public static boolean toggleBookmark(Document note) throws CouchbaseLiteException {
-        Map<String, Object> properties = new HashMap<>(note.getProperties());
+        Map<String, Object> properties = new HashMap<>(note.getUserProperties());
         boolean bookmarked = !isBookmarked(properties);
         properties.put("bookmark", bookmarked);
-        note.putProperties(properties);
+        SavedRevision rev = note.getCurrentRevision().createRevision(properties);
+        assert note.getCurrentRevisionId() == rev.getId();
         return bookmarked;
```
I hope that helps. Let me know if it doesn't resolve your problem (and your problem @heretyk).

**Comment by jackwang1** [comment]
Cool, I'll try this. Seems the android docs are outdated then: http://developer.couchbase.com/documentation/mobile/1.1.0/develop/guides/couchbase-lite/native-api/document/index.html

```java
Document doc = database.getDocument(myDocID);
Map<String, Object> properties = new HashMap<String, Object>();
properties.putAll(doc.getProperties());
properties.put("title", title);
properties.put("notes", notes);
try {
    doc.putProperties(properties);
} catch (CouchbaseLiteException e) {
    e.printStackTrace();
}
```

**Comment by zgramana** [comment]
Thanks, @jackwang1. I've added the `docs` tag so we can update the site.

**Comment by francescopedronomnys** [comment]
@zgramana is it possible that using your method I'm losing the attached documents?
I'm not using Document.getUserProperties() but a custom method that produces the same HashMap as output (checked with debugger) and then I call document.getCurrentRevision().createRevision(hashMap).

(I'm not using getUserProperties() because I've structured my code with a method that acts like a MySQL create or update and receives a Bean as input, so I cannot do the update on the document property by property).

**Comment by zgramana** [comment]
@francescopedronomnys good catch. I went back to double-check and was able to verify the issue, and b) determine the root cause. The tl;dr: should be fixed in master, and in 1.2.

##### Long story:
Before [commit 7e800559e](https://github.com/couchbase/couchbase-lite-java-core/commit/7e800559e9467b5173f89c8477b4ff68487f234e), the `installAttachment` method was sometimes trying to lookup an attachment writer using a SHA1 hash (which, e.g. SG uses) as a key, but it was failing to find it because it was stored by using the MD5 hash as the key instead.
```java
    void installAttachment(AttachmentInternal attachment, Map<String, Object> attachInfo) throws CouchbaseLiteException {
        String digest = (String) attachInfo.get("digest");
        if (digest == null) {
            throw new CouchbaseLiteException(Status.BAD_ATTACHMENT);
        }

        if (pendingAttachmentsByDigest != null && pendingAttachmentsByDigest.containsKey(digest)) {
            BlobStoreWriter writer = pendingAttachmentsByDigest.get(digest);
            try {
                BlobStoreWriter blobStoreWriter = (BlobStoreWriter) writer;
                blobStoreWriter.install();
                attachment.setBlobKey(blobStoreWriter.getBlobKey());
                attachment.setLength(blobStoreWriter.getLength());
            } catch (Exception e) {
                throw new CouchbaseLiteException(e, Status.STATUS_ATTACHMENT_ERROR);
            }
        }
        else{
            Log.w(Database.TAG, "No pending attachment for digest: " + digest);
            throw new CouchbaseLiteException(Status.BAD_ATTACHMENT);
          //^^^^^ This was causing the error, because `pendingAttachmentsByDigest` contained the
          //      an MD5 hash but `digest` was set to a SHA1 hash.
        }
    }
```
After that commit, however, it now works the same way that iOS does, using the BlobKey object instead:
```java
    private void installAttachment(AttachmentInternal attachment) throws CouchbaseLiteException {
        String digest = attachment.getDigest();
        if (digest == null)
            throw new CouchbaseLiteException(Status.BAD_ATTACHMENT);

        Object writer = null;
        if (pendingAttachmentsByDigest != null && pendingAttachmentsByDigest.containsKey(digest)) {
            writer = pendingAttachmentsByDigest.get(digest);
        }

        if (writer != null && writer instanceof BlobStoreWriter) {
            // Found a blob writer, so install the blob:
            BlobStoreWriter blobStoreWriter = (BlobStoreWriter) writer;
            if (!blobStoreWriter.install())
                throw new CouchbaseLiteException(Status.ATTACHMENT_ERROR);
            attachment.setBlobKey(blobStoreWriter.getBlobKey());
            attachment.setPossiblyEncodedLength(blobStoreWriter.getLength());
            // Remove the writer but leave the blob-key behind for future use:
            rememberPendingKey(attachment.getBlobKey(), digest);
            return;
        } else if (writer != null && writer instanceof byte[]) {
            // This attachment was already added, but the key was left behind in the dictionary:
            attachment.setBlobKey(new BlobKey((byte[]) writer));
        } else if (attachments.hasBlobForKey(attachment.getBlobKey())) {
            // It already exists in the blob-store, so it's OK
            return;
        } else {
            Log.w(Database.TAG, "No pending attachment for getDigest: " + digest);
            throw new CouchbaseLiteException(Status.BAD_ATTACHMENT);
        }
    }
```
I'll ask @hideki to confirm.

**Comment by francescopedronomnys** [comment]
@zgramana I don't know if I got it wrong, but building my app using the code from the repository (I'm on master, pulled today) I see the same problem although I expected it to be fixed.
If I use:
```
UnsavedRevision newRev = note.getCurrentRevision().createRevision();
newRev.setProperties(properties);
newRev.save();
```
on a document with a previously added attachment: I loose the attachment while the other properties are updated correctly.

I've also seen this exception the first time I run the application after upgrading from 1.1.0 to the master on the repo:
```
10-26 12:48:09.467 12965-13089/redacted E/RemoteRequest: RemoteRequestCompletionBlock throw Exception java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Set java.util.Map.keySet()' on a null object reference
at com.couchbase.lite.replicator.PusherInternal.uploadMultipartRevision(PusherInternal.java:617)
at com.couchbase.lite.replicator.PusherInternal.access$600(PusherInternal.java:51)
at com.couchbase.lite.replicator.PusherInternal$3.onCompletion(PusherInternal.java:498)
at com.couchbase.lite.support.RemoteRequestRetry$1.completed(RemoteRequestRetry.java:213)
at com.couchbase.lite.support.RemoteRequestRetry$1.onCompletion(RemoteRequestRetry.java:231)
at com.couchbase.lite.support.RemoteRequest.respondWithResult(RemoteRequest.java:301)
at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:250)
at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:103)
[...]
```
This is the line that caused the exception:
```
Map<String, Object> attachments = (Map<String, Object>) revProps.get("_attachments");
        for (String attachmentKey : attachments.keySet()) {
```

**Comment by heretyk** [comment]
Hello @zgramana , @francescopedronomnys,

Just read the latests message.

I am in negociation with Sales team of Couchbase, but i need two clear answers please : 

-the "code" zgramana, doesn't fix the issue...and even attachment are deleted after upload ? Am i correct ?
-If yes, did you identify the issue ? And when can you provide a fix so that we can upload attachment ?

Regards,

**Comment by heretyk** [comment]
My code is 

            /* BEGIN  : Save Picture to Database */

            document = database.getDocument(userId);

                    if(document != null)
                    {
                        java.util.List< Attachment > attachments = document.getCurrentRevision().getAttachments();

                        try {

                            UnsavedRevision newRev = document.getCurrentRevision().createRevision();
                            if (mImageViewNumber==1)
                            {
                                InputStream stream = new FileInputStream(picture1);
                                newRev.setAttachment(fileNamePicture1 + ".jpg", "image/jpeg", stream);
                                if(MainActivity.LOG) Log.i(TAG, "Uploading " + fileNamePicture1 + ".jpg");
                            }
                            if (mImageViewNumber==2)
                            {
                                InputStream stream2 = new FileInputStream(picture2);
                                newRev.setAttachment(fileNamePicture2 + ".jpg", "image/jpeg", stream2);
                                if(MainActivity.LOG) Log.i(TAG, "Uploading " + fileNamePicture2 + ".jpg");
                            }
                            if (mImageViewNumber==3)
                            {
                                InputStream stream3 = new FileInputStream(picture3);
                                newRev.setAttachment(fileNamePicture3 + ".jpg", "image/jpeg", stream3);
                                if(MainActivity.LOG) Log.i(TAG, "Uploading " + fileNamePicture3 + ".jpg");
                            }
                            newRev.save(true);
                        }  catch (FileNotFoundException | CouchbaseLiteException e) {
                            e.printStackTrace();
                        }

            /* CLOSE  : Save Picture to Database */

**Comment by heretyk** [comment]
Dont understand why using Hashmap would change anything :/

**Comment by heretyk** [comment]
Hello @hideki  , @francescopedronomnys,

Do you have an answer to the following questions : 

-the "code" zgramana, doesn't fix the issue...and even attachment are deleted after upload ? Am i correct ?
-If yes, did you identify the issue ? And when can you provide a fix so that we can upload attachment ?

**Comment by heretyk** [comment]
Also i noticed that my app size is growing, and there is a folder called "mydb attachments" in my application's directory on Android ...

Is it possible that this bug would cause lot of revisions locally so that this folder keeps growing ?

**Comment by hideki** [comment]
Hi All,

I have tried to reproduce the issue with using https://github.com/jackwang1/CouchbaseSyncTest . However, I can not reproduce the Exception (`No pending attachment for digest: sha1-xxx`) which is documented in REAME with following the documented instruction. To reproduce the problem, I am using CouchbaseSyncTest sample code with modifying sync gateway IP address and database name (using `db` instead of `foo_bar`),  Sync Gateway v1.1.1 with `examples/basic-walrus-bucket.json` configuration file. Both Sync Gateway and Android ARM emulator (API 19) are running on same my OSX machine. 
To reproduce the problem, it requires unrevealed condition.

I also have tried updating document both client and sync-gateway sides, by keep clicking "CAUSE EXCEPTION" button to update client side document, and keep updating document on sync gateway by clicking "Save Doc" button of Sync Gateway Admin UI (http://localhost:4985/_admin/db/db/documents/94698733-9c1e-42f0-92e3-4b2b54c00233).
By this test, I could observe `CouchbaseLiteException` with conflict. see below.
Because of updating same document at both server and client, it causes document conflict, and CBL throws Exception. However this is expected behavior. 

```
11-13 15:13:39.045 2685-2685/com.samples.couchbaselitesynctest E/Foo: Error accessing CBL
  com.couchbase.lite.CouchbaseLiteException: Conflicts not allowed and there is already an existing doc with id: 94698733-9c1e-42f0-92e3-4b2b54c00233
      at com.couchbase.lite.Database.putRevision(Database.java:3988)
      at com.couchbase.lite.Database.putRevision(Database.java:3923)
      at com.couchbase.lite.Document.putProperties(Document.java:420)
      at com.couchbase.lite.Document.putProperties(Document.java:252)
      at com.samples.couchbaselitesynctest.Note.toggleBookmark(Note.java:130)
      at com.samples.couchbaselitesynctest.MainActivity.onButtonClick(MainActivity.java:43)
      at java.lang.reflect.Method.invokeNative(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:515)
      at android.view.View$1.onClick(View.java:3818)
      at android.view.View.performClick(View.java:4438)
      at android.view.View$PerformClick.run(View.java:18422)
      at android.os.Handler.handleCallback(Handler.java:733)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at android.os.Looper.loop(Looper.java:136)
      at android.app.ActivityThread.main(ActivityThread.java:5001)
      at java.lang.reflect.Method.invokeNative(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:515)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
      at dalvik.system.NativeStart.main(Native Method)
```

To efficiently update document, please use `doc.update(new Document.DocumentUpdater(){...});`
http://developer.couchbase.com/documentation/mobile/current/develop/guides/couchbase-lite/native-api/document/index.html#updating
```
2. update is smarter: it handles the conflict error itself by re-reading the document, then calling your block again with the updated properties, and retrying the save. It will keep retrying until there is no conflict.
````

**Comment by hideki** [comment]
Hi @francescopedronomnys,

Could you please provide us detail steps to reproduce the NullPointerException you encountered?
```
10-26 12:48:09.467 12965-13089/redacted E/RemoteRequest: RemoteRequestCompletionBlock throw Exception java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Set java.util.Map.keySet()' on a null object reference
at com.couchbase.lite.replicator.PusherInternal.uploadMultipartRevision(PusherInternal.java:617)
at com.couchbase.lite.replicator.PusherInternal.access$600(PusherInternal.java:51)
```
Thanks,
Hideki

**Comment by hideki** [comment]
Hi @heretyk,
Sorry for we could not solve your issue for a while.
Is it possible to provide us simple sample app to reproduce the problem you are encountering?
Or could you please provide the code difference from @jackwang1 's sample app?
Thanks,
Hideki

**Comment by zgramana** [comment]
Closing out as a duplicate #699, which has a clean set of reproduction steps.

**Comment by hideki** [comment]
I confirmed #699 is no longer reproducible with current master branch. If you are in hurry, please compile from master branch. Fix will be included in v1.2.0 release.

**Comment by heretyk** [comment]
When is 1.2 release date ?

**Comment by hideki** [comment]
@zgramana can you answer?

**Comment by heretyk** [comment]
@hideki :  

I posted this in the couchbase forum. I paste it here, if you can answer :  

Hello @hideki,

I need your help on 2 informations please : 

- I read on github ticket that the issue is identified, and will be fixed on 1.2.0 GW. Is it correct ? Do you have a release date ?

- On Android devices, the app using CBLite is constantly growing and it reach 500MBin 1 month (app is 25MB at install).
 I opened a topic here : https://forums.couchbase.com/t/local-database-size-growing-size-is-5-times-more-than-cb-server/5855


Also i investigated today on devices file system with `adb`, i noticed that the local db's size  `myApp.cblite` is "normal" (30MB).
But there is a folder called  `myApp attachments`  and it takes the remaining 470 MB .

And as i say in the topic i linked...compacting local db produces this message : 


    17:26:51.354 7532-7604/net.xxxxxE/BlobStore: Error deleting attachment: /data/data/net.xxxxx/files/appdb attachments/temp_attachments

What's your opinon on this ?

 - In your `BlobStore` Class, i see a method  : `public int deleteBlobsExceptWithKeys(List<BlobKey> keysToKeep)`

Is it safe to use this to empty attachments folder ?


Thanks

**Comment by hideki** [comment]
Hi @heretyk,

I can not guess why your app's database is large and attachments were not deleted.

You can use https://github.com/couchbaselabs/CouchbaseLiteViewer to check what kinds of data in your database. Could you please check your data. Also you can look into regular sqlite3 command to see it.

Following is my assumption. Your app creates many conflicts, and they becomes leaf nodes that could not be deleted by `compact()` method. I don't know any guess for delete file failure. Could you please past entire stack trace?

This new issue and this thread could be different topic. Could you please reopen new ticket with detailed information?

Thanks,
Hideki

**Comment by hideki** [comment]
> In your BlobStore Class, i see a method : public int deleteBlobsExceptWithKeys(List<BlobKey> keysToKeep)
> Is it safe to use this to empty attachments folder ?

Missing attachments, that should exists, might cause another problems.

**Comment by zgramana** [comment]
@heretyk we don't have a public release date to share. However, you should expect it soon. Keep an eye out for a preview.

**Comment by heretyk** [comment]
@hideki : 
"Your app creates many conflicts, and they become leaf nodes that could not be deleted by compact() method. I don't know any guess for delete file failure."

I think you are right.

I checked on two  devices (Huawei Y-550L01 and HTC Desire HD) with the last version of our code. The HTC is pretty old, and in bad shape.The installation was fresh and new on both. 
Only on the HTC, i've got this error...On the Huawei, this does not occurs.
And the data replicated on both are the same.

Error message is the same, only this : "11-19 15:22:27.648  12587-12615/net.xxxxx E/BlobStore﹕ Error deleting attachment: /data/data/net.xxxxxx/files/truemeetdb attachments/temp_attachments"

Data size on the Huawei is only 15MB while it's 25MB already on the HTC.

Any suggestion to troubleshoot this ? Thanks

Two side questions please : 

1 : In theory, how much documents can i expect to have on CBlite in my app ithout impacting seriously performance ?  (We  may have  1.10e6 doc of 1 MB in 2 or 3 years) ?

2 : By any chance do you know a way to access  my app "data" folder on a non-rooted device ? I use a legacy OS on one phone and i don't want to root it at the moment.

Regards,

**Comment by heretyk** [comment]
@hideki : 

Just made some tests on another device and the same error occurs.  Fresh  new installl.

"Error deleting attachment: /data/data/net.truemeet/files/truemeetdb attachments/temp_attachments"

I  think it is related to the issue with attachments of this very topic.

As the uplade attachment produces an issue, then as you said, there are revisions in conflict.
And it produces 2 things : 

-The error i get probably because the attachment  is like "locked" and cannot be deleted.
So the compacting  cannot be fully achieved.

- The  db create other "leaf" or "branch"...and so the local DB keeps growing (especially if others Docs replicated to the local devices suffers the same "behavior)

So i wonder if i really should open another ticket or not. For me, it is due to the "attachment issue" that i cannot compact local DB and that it keeps growing.

@hideki, @zgramana : what's your opinion on this ?

**Comment by hideki** [comment]
> The error i get probably because the attachment is like "locked" and cannot be deleted.
So the compacting cannot be fully achieved.

As you wrote, the attachment file is opened when compact() is called.

> The db create other "leaf" or "branch"...and so the local DB keeps growing (especially if others Docs replicated to the local devices suffers the same "behavior)

To avoid this problem, you need to delete conflicting revisions. Please use following APIs.

`List<SavedRevision>  Document.getConflictingRevisions()`
http://developer.couchbase.com/documentation/mobile/1.1.0/develop/references/couchbase-lite/couchbase-lite/document/document/index.html#savedrevision-conflictingrevisions--get-

`SavedRevision SavedRevision.deleteDocument()`
http://developer.couchbase.com/documentation/mobile/1.1.0/develop/references/couchbase-lite/couchbase-lite/revision/saved-revision/index.html#savedrevision-deletedocument

**Comment by heretyk** [comment]
Thanks @hideki,

I will implement this. I believe this should be better done before compaction...right ?

Regards,

**Comment by hideki** [comment]
@heretyk,

Yes, please call `SavedRevision.deleteDocument()` before calling `compact()`, otherwise no impact.

Thanks!

**Comment by hideki** [comment]
Hi @heretyk ,

FYI: 
V1.1.0 has issue with `Database.compact()` method. See https://github.com/couchbase/couchbase-lite-android/issues/685

Thanks!

**Comment by hideki** [comment]
Hi @heretyk,

I fixed the `Database.compact()` issue and sent PR for master branch. If you need fix for v1.1.0, can you apply https://github.com/couchbase/couchbase-lite-java-core/pull/828/files, and build by yourself? This fix will be included in v1.2.0 release.

**Comment by heretyk** [comment]
@hideki : Just saw your message.

Thanks for the updates, much appreciated.

So from 1.2.0 we will be able to upload attachments AND database compaction will works and run automatically without the need of calling 'Database.compact()' .
Am i right ?

Also, until 1.2.0, i can perfectly call  'SavedRevision.deleteDocument()' and then run 'Database.compact()', 24h later (at app restart) for example. 
Correct ?

**Comment by hideki** [comment]
@heretyk,

> So from 1.2.0 we will be able to upload attachments AND database compaction will works and run automatically without the need of calling Database.compact() .indent preformatted text by 4 spaces`
Am i right ?

- upload attachment issue and `Database.compact()` issue are two different issue.
- Upload attachment issue you encountered should be fixed with v1.2.0. Please test this as soon as v1.2 will be released.
- `Database.compact()` is not automatically executed with current master branch without fixing https://github.com/couchbase/couchbase-lite-java-core/issues/840

> Also, until 1.2.0, i can perfectly call SavedRevision.deleteDocument() and then run Database.compact() whenever i want then ? I suppose it doesn't matter if it just right after deleting revisions or at the next app restart for example...

- Yes

**Comment by VasuInukollu** [comment]
@hideki 
I am having the problem referred by @francescopedronomnys 

https://github.com/couchbase/couchbase-lite-android/issues/1719
